apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bbtest-app
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: bbtest-app
  endpoints:
  - port: web
